
if patched_font_in_use; then
  TMUX_POWERLINE_SEPARATOR_LEFT_BOLD=" | "
  TMUX_POWERLINE_SEPARATOR_LEFT_THIN=" - "
  TMUX_POWERLINE_SEPARATOR_RIGHT_BOLD=" | "
  TMUX_POWERLINE_SEPARATOR_RIGHT_THIN=" - "
else
  TMUX_POWERLINE_SEPARATOR_LEFT_BOLD=" "
  TMUX_POWERLINE_SEPARATOR_LEFT_THIN=" "
  TMUX_POWERLINE_SEPARATOR_RIGHT_BOLD=" "
  TMUX_POWERLINE_SEPARATOR_RIGHT_THIN=" "
fi

TMUX_POWERLINE_DEFAULT_BACKGROUND_COLOR=${TMUX_POWERLINE_DEFAULT_BACKGROUND_COLOR:-'16'}
TMUX_POWERLINE_DEFAULT_FOREGROUND_COLOR=${TMUX_POWERLINE_DEFAULT_FOREGROUND_COLOR:-'255'}

TMUX_POWERLINE_DEFAULT_LEFTSIDE_SEPARATOR=${TMUX_POWERLINE_DEFAULT_LEFTSIDE_SEPARATOR:-$TMUX_POWERLINE_SEPARATOR_RIGHT_BOLD}
TMUX_POWERLINE_DEFAULT_RIGHTSIDE_SEPARATOR=${TMUX_POWERLINE_DEFAULT_RIGHTSIDE_SEPARATOR:-$TMUX_POWERLINE_SEPARATOR_LEFT_BOLD}


# Format: segment_name background_color foreground_color [non_default_separator]

if [ -z $TMUX_POWERLINE_LEFT_STATUS_SEGMENTS ]; then
  TMUX_POWERLINE_LEFT_STATUS_SEGMENTS=(
    "battery 16 47" \
    "tmux_session_info 16 11" \
    # "hostname 16 33" \
    "pwd 16 33" \
    # "ifstat 30 255" \
    # "ifstat_sys 30 255" \

    # "vcs_branch 29 88" \
    # "vcs_compare 60 255" \
    # "vcs_staged 64 255" \
    # "vcs_modified 9 255" \
    # "vcs_others 245 0" \
  )
fi

if [ -z $TMUX_POWERLINE_RIGHT_STATUS_SEGMENTS ]; then
  TMUX_POWERLINE_RIGHT_STATUS_SEGMENTS=(
    #"earthquake 3 0" \
    #"macos_notification_count 29 255" \
    # "mailcount 9 255" \
    # "now_playing 16 37" \
    # "cpu 16 136" \
    # "load 237 167" \
    # "tmux_mem_cpu_load 16 136" \
    # "weather 37 255" \
    #"rainbarf 0 ${TMUX_POWERLINE_DEFAULT_FOREGROUND_COLOR}" \
    #"xkb_layout 125 117" \
    "date_day 16 33" \
    "date 16 11 ${TMUX_POWERLINE_SEPARATOR_LEFT_THIN}" \
    "time 16 47 ${TMUX_POWERLINE_SEPARATOR_LEFT_THIN}" \
    #"utc_time 16 136 ${TMUX_POWERLINE_SEPARATOR_LEFT_THIN}" \
  )
fi
