export ZSH="/Users/sldobri/.oh-my-zsh"
export ZSH_CUSTOM="$ZSH/custom"
export NODE_ENV="development"
# export EDITOR="nvim"
export LANG="en_US.UTF-8"
# export NVIM_TUI_ENABLE_TRUE_COLOR=1

export PATH=$HOME/bin:/usr/local/bin:$PATH

export PATH="/usr/local/opt/node@14/bin:$PATH"
export LDFLAGS="-L/usr/local/opt/node@14/lib"
export CPPFLAGS="-I/usr/local/opt/node@14/include"

# export PATH="/usr/local/Cellar/node/16.0.0/bin:$PATH"
export PATH="/usr/bin:$PATH"
export PATH="/usr/local/sbin:$PATH"
export PATH="/usr/local/bin:$PATH"
export PATH="$PATH:$HOME/.rvm/bin"
export PATH="/usr/local/opt/luajit-openresty/bin:$PATH"
# export PATH="/usr/local/opt/mongodb-community@3.4/bin:$PATH"


DISABLE_LS_COLORS="true"
HIST_STAMPS="yyyy-mm-dd"
ENABLE_CORRECTION="false"
COMPLETION_WAITING_DOTS="true"
DISABLE_UNTRACKED_FILES_DIRTY="true"
ZSH_DISABLE_COMPFIX="true"
ZSH_THEME="avit"

# source $ZSH/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
source $ZSH/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh
# source $ZSH/themes/powerlevel10k/powerlevel10k.zsh-theme
# [[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.


plugins=(
  # z
  git
  osx
  # zsh-syntax-highlighting
  zsh-autosuggestions
)


# ZSH
alias zsh="nvim $HOME/.zshrc"
alias sz="source $HOME/.zshrc"


# aliases
alias ls="ls -la"
alias lh="ls -lhtr"
alias history="fc -il 1i"
alias c="clear"
alias f="open ."
alias rm="rm -ifr"
alias cpu="top -o cpu"   # CPU
alias mem="top -o rsize" # Memory


# Editors
alias v="nvim"
alias s="subl"
alias c="code --disable-gpu"

# publish vs code
# alias publish='vsce publish -p m3nr6makgy5qmecy3wmmutlujbbs6om3mxygbhxdi4g6mjk63b5q'

# Busca
alias psa="ps aux"
alias psg="ps aux | grep "

alias dot-bkp="$HOME/Dropbox/Mac/Scripts/dot-bkp.sh"
alias dot-restore="$HOME/Dropbox/Mac/Settings/dot-restore.sh"

# remove the ‘application downloaded from the internet’ error message
alias xatcr="xattr -cr "


# download videos from webpage
alias ydl="youtube-dl"


# moving
alias ..="cd .."
alias home="cd $HOME/"


# dotfiles
alias dot="cd $HOME/.dotfiles"


# Site
alias sm="cd /Volumes/Sites/site-modelo-2021 && clear"
alias mp="cd /Volumes/Sites/my-project && clear"
alias anp="cd /Volumes/Sites/agua_nova_piscinas && clear"
alias r3c="cd /Volumes/Sites/rancho_tres_coracoes_2019 && clear"
alias q1s="cd /Volumes/Sites/quero1site_2020 && clear"
alias sca="cd /Volumes/Sites/shopping_da_carne_2021 && clear"
alias ptu="cd /Volumes/Sites/pousada_do_tucunare_2020 && clear"
alias sen="cd /Volumes/Sites/santos_e_nascimento_2020 && clear"

# Code
alias as="cd /Volumes/Code/auton/server && clear"
alias ac="cd /Volumes/Code/auton/client && clear"
alias eu="cd /Volumes/Code/urban-octo-eureka && clear"
alias esh="cd /Volumes/Code/e-shop && clear"
alias low="cd /Volumes/Code/nuxt-express-auth-lowdb-admin && clear"
alias cds="cd /Volumes/Code/car-dealership-2020 && clear"

# old

# alias fag="cd /Volumes/Sites/filmAgora_2020 && clear"
# alias dmo="cd /Volumes/Sites/dular_moveis_2020 && clear"
# alias cor="cd /Volumes/Sites/colchoes_oriental_2020 && clear"
# alias per="cd /Volumes/Sites/psicologa_erica_rover_2020 && clear"
# alias avp="cd /Volumes/Sites/arte_visual_propag_2021 && clear"
# alias zzz="cd /Volumes/Sites/blog && clear"
# alias cda="cd /Volumes/WS/car-dealership-api-2020 && clear"
# alias cdd="cd /Volumes/WS/car-dealership-adm-2020 && clear"


# brew
alias bi="brew install"
alias bs="brew search"
alias bu="brew uninstall"
alias bc="brew cleanup"
alias bubu="brew update && brew upgrade && brew cleanup && brew doctor"


# npm
alias nr="npm run"
alias nrf="npm run fix"
alias nrd="npm run dev"
alias nrb="npm run build"
alias nrg="npm run generate && open /Applications/ForkLift.app"
alias nrs="npm run serve"
alias nrstt="npm run start"
alias nrss="npm run start:api"
alias nrsc="npm run start:app"
alias ni="npm install"
alias nid="npm install --save-dev"
alias nig="npm install -g"
alias nu="npm uninstall"
alias nug="npm uninstall -g"
alias nls="npm ls -g" # List installed packages
alias nls="npm ls" # List installed packages
alias nls="npm prune" # Remove un-used packages from node_modules folder
alias nup="npm update" # Update all packages listed in package.json
alias nrdup="npm dedupe" # Remove duplicate packages from node_modules
alias nclean="npm cache clean -f" # Clean npm cache


# Git
alias gaa="git add ."
alias gs="git status --short"
alias gl="git log --color --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit --branches"
alias gc="git commit -m"
alias gp="git push"
alias gps="git push && git status --short"
alias gnah="git reset --hard && git clean -df"
alias gaac="rm -rf dist && git add . && git commit -m"
alias gaacz="rm -rf dist && git add . && git cz"
alias gsync="git pull && git push"


function mk-cd(){
  mkdir "$*"
  cd "$*"
}

function find-node-modules(){
 find . -name node_modules -type d
}  

function git-init(){
  git init
  gaac "first commit"
  git remote add origin "$*"
  git remote set-url origin "$*"
  git push -u origin master
}
# git remote add origin https://github.com/dobbbri/pscologa_erica_rover_2020.git
# git remote set-url origin git@github.com:dobbbri/pscologa_erica_rover_2020.git

source $ZSH/oh-my-zsh.sh

# source ~/.zshrc


alias luamake=/Users/sldobri/.config/nvim/ls/lua-language-server/3rd/luamake/luamake
