export ZSH="/Users/sldobri/.oh-my-zsh"
export ZSH_CUSTOM="$ZSH/custom"
export EDITOR="nvim"
export LANG="en_US.UTF-8"
export NEOVIM_BIN="/opt/local/bin/nvim"
export DEFAULT_FONT="Operator Mono:h22"
LC_CTYPE=en_US.UTF-8
LC_ALL=en_US.UTF-8

export PATH="/usr/bin:$PATH"
export PATH="/usr/local/sbin:$PATH"
export PATH="/usr/local/bin:$PATH"
export PATH="/opt/local/lib/node_modules:$PATH"
export PATH="$HOME/.rvm/bin:$PATH"
export PATH="/opt/local/bin:$PATH"
export PATH="/opt/local/sbin:$PATH"
export PATH="/Users/sldobri/Library/Python/3.10/bin:$PATH"
export PATH="/Users/sldobri/nvim-macos/bin:$PATH"

DISABLE_LS_COLORS="true"
HIST_STAMPS="yyyy-mm-dd"
ENABLE_CORRECTION="false"
COMPLETION_WAITING_DOTS="true"
DISABLE_UNTRACKED_FILES_DIRTY="true"
ZSH_DISABLE_COMPFIX="true"
ZSH_THEME=""  #"avit"  #"refined"

fpath+=($HOME/.oh-my-zsh/plugins/pure)
autoload -U promptinit; promptinit
prompt pure

source $ZSH/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh
# source $ZSH/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
# source $ZSH/themes/powerlevel10k/powerlevel10k.zsh-theme
# [[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.

plugins=(
  z
  git
  macos
  # zsh-syntax-highlighting
  zsh-autosuggestions
)

# ZSH
# rename zsh to zshv, because zsh show errors when update
alias zshv="v $HOME/.zshrc"
alias sz="source $HOME/.zshrc"

# aliases
alias ls="ls -aG"
alias la="ls -laG"
alias lh="ls -lhtrG"
alias history="fc -il 1i"
alias c="clear"
alias f="open ."
alias rm="rm -ifr"
alias cpu="top -o cpu"   # CPU
alias mem="top -o rsize" # Memory

# Editors
alias v="nvim"
alias s="subl"
alias c="code --disable-gpu"

# Busca
alias psa="ps aux"
alias psg="ps aux | grep "

# remove the ‘application downloaded from the internet’ error message
alias xatcr="xattr -cr "

# download videos from webpage
alias ydl="youtube-dl"

alias where="which"

# moving
alias ..="cd .."
alias home="cd $HOME/"
alias codes="cd /Volumes/data/codes"
alias sites="cd /Volumes/data/sites"

# dotfiles
alias dot="cd $HOME/.dotfiles"
alias dotv="dot && v"
alias vv="cd $HOME/.dotfiles/nvim && v"

# Code
alias qs="cd /Volumes/data/codes/quasar-supabase && clear"
alias qsv="qs && v"
alias ac="cd /Volumes/data/codes/astro-crash-course && clear"
alias acv="ac && v"

# Site
alias pc="cd /Volumes/data/sites/pet_care_2022 && clear"
alias pcv="pc && v"
alias sm="cd /Volumes/data/sites/site-modelo-2021 && clear"
alias mp="cd /Volumes/data/sites/my-project && clear"
alias anp="cd /Volumes/data/sites/agua_nova_piscinas && clear"
alias r3c="cd /Volumes/data/sites/rancho_tres_coracoes_2019 && clear"
alias ptu="cd /Volumes/data/sites/pousada_do_tucunare_2020 && clear"
alias q1s="cd /Volumes/data/sites/quero1site_2020 && clear"
# alias sca="cd /Volumes/data/sites/shopping_da_carne_2021 && clear"
# alias sen="cd /Volumes/data/sites/santos_e_nascimento_2020 && clear"

# old

# alias fag="cd /Volumes/data/sites/filmAgora_2020 && clear"
# alias dmo="cd /Volumes/data/sites/dular_moveis_2020 && clear"
# alias cor="cd /Volumes/data/sites/colchoes_oriental_2020 && clear"
# alias per="cd /Volumes/data/sites/psicologa_erica_rover_2020 && clear"
# alias avp="cd /Volumes/data/sites/arte_visual_propag_2021 && clear"
# alias zzz="cd /Volumes/data/sites/blog && clear"
# alias cda="cd /Volumes/WS/car-dealership-api-2020 && clear"
# alias cdd="cd /Volumes/WS/car-dealership-adm-2020 && clear"

# brew
# alias bi="brew install"
# alias bs="brew search"
# alias bu="brew uninstall"
# alias bc="brew cleanup"
# alias bubu="brew update && brew upgrade && brew cleanup && brew doctor"

# npm
alias nr="npm run"
alias nrf="npm run fix"
alias nrd="npm run dev"
alias nrb="npm run build"
alias nrg="npm run generate && open /Applications/ForkLift.app"
# alias nrs="npm run serve"
alias nrs="npm run start"
# alias nrss="npm run start:api"
# alias nrsc="npm run start:app"
alias ni="npm install"
alias nid="npm install --save-dev"
alias nig="sudo npm install -g"
alias nu="npm uninstall"
alias nug="sudo npm uninstall -g"
alias nls="npm ls -g" # List installed packages
alias nls="npm ls" # List installed packages
alias nlp="npm prune" # Remove un-used packages from node_modules folder
alias nup="npm update" # Update all packages listed in package.json
alias nrdup="npm dedupe" # Remove duplicate packages from node_modules
alias nclean="npm cache clean -f" # Clean npm cache

# Git
alias gaa="git add ."
alias gs="git status --short"
alias gl="git log --color --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit --branches"
alias gc="git commit -m"
alias gp="git push"
alias gps="git push && git status --short"
alias gnah="git reset --hard && git clean -df"
alias gaac="rm -rf dist && git add . && git commit -m"
alias gaacz="rm -rf dist && git add . && git cz"
alias gsync="git pull && git push"

function mk-cd(){
  mkdir "$*"
  cd "$*"
}

function find-node-modules(){
 find . -name node_modules -type d
}

function git-init(){
  git init
  gaac "first commit"
  git remote add origin "$*"
  git remote set-url origin "$*"
  git push -u origin master
}

function nvim-up(){
 rm -rf $HOME/.nvim-macos/
 # curl -LO https://github.com/neovim/neovim/releases/download/nightly/nvim-macos.tar.gz
 curl -LO https://github.com/neovim/neovim/releases/download/v0.7.2/nvim-macos.tar.gz
 tar xzf nvim-macos.tar.gz
 mv nvim-macos $HOME/.nvim-macos
 rm nvim-macos.tar.gz
 v
}

source $ZSH/oh-my-zsh.sh

# eval "$(starship init zsh)"
